set_property IOSTANDARD LVCMOS33 [get_ports {an_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {inNum[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inNum[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inNum[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inNum[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inNum[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inNum[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inNum[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inNum[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sevSeg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sevSeg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sevSeg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sevSeg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sevSeg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sevSeg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sevSeg_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN W5 [get_ports clk]

set_property PACKAGE_PIN V17 [get_ports {inNum[0]}]
set_property PACKAGE_PIN V16 [get_ports {inNum[1]}]
set_property PACKAGE_PIN W16 [get_ports {inNum[2]}]
set_property PACKAGE_PIN W17 [get_ports {inNum[3]}]
set_property PACKAGE_PIN W15 [get_ports {inNum[4]}]
set_property PACKAGE_PIN V15 [get_ports {inNum[5]}]
set_property PACKAGE_PIN W14 [get_ports {inNum[6]}]
set_property PACKAGE_PIN W13 [get_ports {inNum[7]}]

set_property PACKAGE_PIN W7 [get_ports {sevSeg_out[0]}]						
set_property PACKAGE_PIN W6 [get_ports {sevSeg_out[1]}]						
set_property PACKAGE_PIN U8 [get_ports {sevSeg_out[2]}]						
set_property PACKAGE_PIN V8 [get_ports {sevSeg_out[3]}]					
set_property PACKAGE_PIN U5 [get_ports {sevSeg_out[4]}]					
set_property PACKAGE_PIN V5 [get_ports {sevSeg_out[5]}]					
set_property PACKAGE_PIN U7 [get_ports {sevSeg_out[6]}]					

set_property PACKAGE_PIN U2 [get_ports {an_out[0]}]					
set_property PACKAGE_PIN U4 [get_ports {an_out[1]}]					
set_property PACKAGE_PIN V4 [get_ports {an_out[2]}]					
set_property PACKAGE_PIN W4 [get_ports {an_out[3]}]					
